### ISSUE TITLE
about data input 

### ISSUE THREAD

**Issue by nbnbhwyy** [combio-dku/RCTIcollection#1]
Thank you for your excellent work!

I get the following error when I run the scCATCH and scType methods in the RCTIcollection_example.ipynb file, would appreciate your help!

Error in createscCATCH(Seurat_obj@assays$RNA@data, cluster = Seurat_obj@meta.data$clusters): "data"槽名不存在于"Assay5"类别对象中（The slot name does not exist in the "Assay5" class object.）
Traceback:

1. identify_celltypes_using_marker(df_data, mkr, method = method)
2. run_sccatch(df_data, df_mkr_mat = df_mkr, Tissues = c(), Species = "Human", 
 .     N_pca = N_pca, Clustering_resolution = Clustering_resolution, 
 .     N_features = N_features)
3. createscCATCH(Seurat_obj@assays$RNA@data, cluster = Seurat_obj@meta.data$clusters)

In addition, since different methods have a threshold for predicting the UNKNOWN type. Therefore, I would like to ask if there is a parameter that will make all models not predict the UNKNOWN type, or control the threshold size with some parameter.

**Comment by combio-dku** [comment]
Hi, thank you for the interest in RCTIcollection.
For the first issue, I think the problem might be that you are using newer version of R and Seurat that is not compatible with scCatch and scType. Different from other tools, both scType and scCatch take Seurat object as its input.  I tested RCTIcollection with R version 4.0.2 with which, I remember, the compatible Seurat version was 4. 
Since I don't have much time to update RCTIcollection to make it compatible with newer Seurat version, I suggest you to create an environment (for example using anaconda3) with R version 4.0.2 and Seurat version 4 to avoid the above error.

For the second issue, unfortunately there is no such parameters in RCTIcollection. I tried to use all the methods with their default settings, without considering what specific parameters they have. In many cases, the default setting performs the best and it is also the case in HiCAT.  I understand your intention. But, even if there exist such parameters that make each method not to issue UNKNOWN type, it wouldn't be a good idea when compare their performance since with different parameter setting, they may not work well and, sometimes, gives us unexpected results.

Feel free to raise another issue if you need any other assistance.
All the best

**Comment by nbnbhwyy** [comment]
Thank you for your help.
